projects:
  Anon-Server:
    schemaPath: prisma.graphql
    extensions:
      endpoints:
        default: "http://localhost:4466"
        # online: "https://eu1.prisma.sh/p-g-nithin-reddy-7a1691/Anon-Server/dev"
